### ISSUE TITLE
v1 Checklist

### ISSUE THREAD

**Issue by ar-x** [ar-x/turtlestarter#1]
* [ ] Home page: Show campaigns
* [ ] Home page: Should be able to sort listed campaigns by a bunch a criteria
* [ ] Login via Discord
* [ ] Campaign detail page: Like
* [ ] Campaign detail page: Post comments
* [ ] Campaign detail page: Post updates
* [ ] Campaign detail page: Pledge
* [ ] Manually escrowed pledging system

**Comment by ar-x** [comment]
<img width="1033" alt="turtlestarter crowdfund ideas" src="https://user-images.githubusercontent.com/37969038/41824440-d22b8d80-77c4-11e8-9291-9724c2ac2483.png">
